import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio — VibecodeKit",
  description: "Generated by VibecodeKit scaffold engine (preset: portfolio)",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className="bg-white text-slate-900 antialiased">
        {children}
      </body>
    </html>
  );
}
