import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SaaS — VibecodeKit",
  description: "Generated by VibecodeKit scaffold engine (preset: saas)",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className="bg-slate-50 text-slate-900 antialiased">{children}</body>
    </html>
  );
}
