import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View } from "react-native";

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>VibecodeKit Mobile</Text>
      <Text style={styles.subtitle}>Generated by scaffold engine</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#fff" },
  title: { fontSize: 28, fontWeight: "bold" },
  subtitle: { marginTop: 8, color: "#666" },
});
