"use client";

import { useState } from "react";

export default function Home() {
  const [email, setEmail] = useState("");
  const [done, setDone] = useState(false);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    // TODO: replace with real provider (Supabase, Resend, ConvertKit, …)
    await new Promise((r) => setTimeout(r, 300));
    setDone(true);
  }

  return (
    <main className="min-h-screen bg-gradient-to-b from-white to-slate-100 px-6 py-24">
      <div className="mx-auto max-w-3xl text-center">
        <h1 className="text-5xl font-bold tracking-tight text-slate-900">
          Ship faster with VibecodeKit
        </h1>
        <p className="mt-4 text-lg text-slate-600">
          A scaffolded starter for your next idea — generated by the VibecodeKit
          scaffold engine.
        </p>

        <ul className="mt-12 grid gap-6 sm:grid-cols-3 text-left">
          {[
            { t: "Fast", d: "Pre-wired Next.js 15 + Tailwind." },
            { t: "Safe", d: "Permission engine + auto-commit hook." },
            { t: "Vietnamese", d: "VN error translator + faker." },
          ].map((f) => (
            <li key={f.t} className="rounded-xl bg-white p-6 shadow">
              <h2 className="font-semibold">{f.t}</h2>
              <p className="mt-1 text-sm text-slate-600">{f.d}</p>
            </li>
          ))}
        </ul>

        {done ? (
          <p className="mt-12 text-emerald-600">Thanks — we'll be in touch!</p>
        ) : (
          <form onSubmit={onSubmit} className="mt-12 flex max-w-md mx-auto gap-2">
            <input
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
              className="flex-1 rounded-lg border border-slate-300 px-4 py-2"
            />
            <button
              type="submit"
              className="rounded-lg bg-slate-900 px-5 py-2 text-white"
            >
              Notify me
            </button>
          </form>
        )}
      </div>
    </main>
  );
}
